// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payload.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_payload_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_payload_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_payload_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_payload_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_payload_2eproto;
class Payload;
struct PayloadDefaultTypeInternal;
extern PayloadDefaultTypeInternal _Payload_default_instance_;
class PayloadResponse;
struct PayloadResponseDefaultTypeInternal;
extern PayloadResponseDefaultTypeInternal _PayloadResponse_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::Payload* Arena::CreateMaybeMessage<::Payload>(Arena*);
template<> ::PayloadResponse* Arena::CreateMaybeMessage<::PayloadResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class Payload final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Payload) */ {
 public:
  inline Payload() : Payload(nullptr) {}
  ~Payload() override;
  explicit PROTOBUF_CONSTEXPR Payload(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Payload(const Payload& from);
  Payload(Payload&& from) noexcept
    : Payload() {
    *this = ::std::move(from);
  }

  inline Payload& operator=(const Payload& from) {
    CopyFrom(from);
    return *this;
  }
  inline Payload& operator=(Payload&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Payload& default_instance() {
    return *internal_default_instance();
  }
  static inline const Payload* internal_default_instance() {
    return reinterpret_cast<const Payload*>(
               &_Payload_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Payload& a, Payload& b) {
    a.Swap(&b);
  }
  inline void Swap(Payload* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Payload* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Payload* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Payload>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Payload& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Payload& from) {
    Payload::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Payload* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Payload";
  }
  protected:
  explicit Payload(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kPayloadIdFieldNumber = 2,
    kLeftOperandFieldNumber = 3,
    kRightOperandFieldNumber = 4,
  };
  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // int32 payload_id = 2;
  void clear_payload_id();
  int32_t payload_id() const;
  void set_payload_id(int32_t value);
  private:
  int32_t _internal_payload_id() const;
  void _internal_set_payload_id(int32_t value);
  public:

  // int32 left_operand = 3;
  void clear_left_operand();
  int32_t left_operand() const;
  void set_left_operand(int32_t value);
  private:
  int32_t _internal_left_operand() const;
  void _internal_set_left_operand(int32_t value);
  public:

  // int32 right_operand = 4;
  void clear_right_operand();
  int32_t right_operand() const;
  void set_right_operand(int32_t value);
  private:
  int32_t _internal_right_operand() const;
  void _internal_set_right_operand(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Payload)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    int32_t payload_id_;
    int32_t left_operand_;
    int32_t right_operand_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_payload_2eproto;
};
// -------------------------------------------------------------------

class PayloadResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PayloadResponse) */ {
 public:
  inline PayloadResponse() : PayloadResponse(nullptr) {}
  ~PayloadResponse() override;
  explicit PROTOBUF_CONSTEXPR PayloadResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PayloadResponse(const PayloadResponse& from);
  PayloadResponse(PayloadResponse&& from) noexcept
    : PayloadResponse() {
    *this = ::std::move(from);
  }

  inline PayloadResponse& operator=(const PayloadResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline PayloadResponse& operator=(PayloadResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PayloadResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const PayloadResponse* internal_default_instance() {
    return reinterpret_cast<const PayloadResponse*>(
               &_PayloadResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PayloadResponse& a, PayloadResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(PayloadResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PayloadResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PayloadResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PayloadResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PayloadResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PayloadResponse& from) {
    PayloadResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PayloadResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PayloadResponse";
  }
  protected:
  explicit PayloadResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kPayloadIdFieldNumber = 2,
    kSolutionFieldNumber = 3,
  };
  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // int32 payload_id = 2;
  void clear_payload_id();
  int32_t payload_id() const;
  void set_payload_id(int32_t value);
  private:
  int32_t _internal_payload_id() const;
  void _internal_set_payload_id(int32_t value);
  public:

  // int32 solution = 3;
  void clear_solution();
  int32_t solution() const;
  void set_solution(int32_t value);
  private:
  int32_t _internal_solution() const;
  void _internal_set_solution(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:PayloadResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    int32_t payload_id_;
    int32_t solution_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_payload_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Payload

// string name = 1;
inline void Payload::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& Payload::name() const {
  // @@protoc_insertion_point(field_get:Payload.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Payload::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Payload.name)
}
inline std::string* Payload::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:Payload.name)
  return _s;
}
inline const std::string& Payload::_internal_name() const {
  return _impl_.name_.Get();
}
inline void Payload::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* Payload::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* Payload::release_name() {
  // @@protoc_insertion_point(field_release:Payload.name)
  return _impl_.name_.Release();
}
inline void Payload::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Payload.name)
}

// int32 payload_id = 2;
inline void Payload::clear_payload_id() {
  _impl_.payload_id_ = 0;
}
inline int32_t Payload::_internal_payload_id() const {
  return _impl_.payload_id_;
}
inline int32_t Payload::payload_id() const {
  // @@protoc_insertion_point(field_get:Payload.payload_id)
  return _internal_payload_id();
}
inline void Payload::_internal_set_payload_id(int32_t value) {
  
  _impl_.payload_id_ = value;
}
inline void Payload::set_payload_id(int32_t value) {
  _internal_set_payload_id(value);
  // @@protoc_insertion_point(field_set:Payload.payload_id)
}

// int32 left_operand = 3;
inline void Payload::clear_left_operand() {
  _impl_.left_operand_ = 0;
}
inline int32_t Payload::_internal_left_operand() const {
  return _impl_.left_operand_;
}
inline int32_t Payload::left_operand() const {
  // @@protoc_insertion_point(field_get:Payload.left_operand)
  return _internal_left_operand();
}
inline void Payload::_internal_set_left_operand(int32_t value) {
  
  _impl_.left_operand_ = value;
}
inline void Payload::set_left_operand(int32_t value) {
  _internal_set_left_operand(value);
  // @@protoc_insertion_point(field_set:Payload.left_operand)
}

// int32 right_operand = 4;
inline void Payload::clear_right_operand() {
  _impl_.right_operand_ = 0;
}
inline int32_t Payload::_internal_right_operand() const {
  return _impl_.right_operand_;
}
inline int32_t Payload::right_operand() const {
  // @@protoc_insertion_point(field_get:Payload.right_operand)
  return _internal_right_operand();
}
inline void Payload::_internal_set_right_operand(int32_t value) {
  
  _impl_.right_operand_ = value;
}
inline void Payload::set_right_operand(int32_t value) {
  _internal_set_right_operand(value);
  // @@protoc_insertion_point(field_set:Payload.right_operand)
}

// -------------------------------------------------------------------

// PayloadResponse

// string name = 1;
inline void PayloadResponse::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& PayloadResponse::name() const {
  // @@protoc_insertion_point(field_get:PayloadResponse.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PayloadResponse::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PayloadResponse.name)
}
inline std::string* PayloadResponse::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:PayloadResponse.name)
  return _s;
}
inline const std::string& PayloadResponse::_internal_name() const {
  return _impl_.name_.Get();
}
inline void PayloadResponse::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* PayloadResponse::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* PayloadResponse::release_name() {
  // @@protoc_insertion_point(field_release:PayloadResponse.name)
  return _impl_.name_.Release();
}
inline void PayloadResponse::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PayloadResponse.name)
}

// int32 payload_id = 2;
inline void PayloadResponse::clear_payload_id() {
  _impl_.payload_id_ = 0;
}
inline int32_t PayloadResponse::_internal_payload_id() const {
  return _impl_.payload_id_;
}
inline int32_t PayloadResponse::payload_id() const {
  // @@protoc_insertion_point(field_get:PayloadResponse.payload_id)
  return _internal_payload_id();
}
inline void PayloadResponse::_internal_set_payload_id(int32_t value) {
  
  _impl_.payload_id_ = value;
}
inline void PayloadResponse::set_payload_id(int32_t value) {
  _internal_set_payload_id(value);
  // @@protoc_insertion_point(field_set:PayloadResponse.payload_id)
}

// int32 solution = 3;
inline void PayloadResponse::clear_solution() {
  _impl_.solution_ = 0;
}
inline int32_t PayloadResponse::_internal_solution() const {
  return _impl_.solution_;
}
inline int32_t PayloadResponse::solution() const {
  // @@protoc_insertion_point(field_get:PayloadResponse.solution)
  return _internal_solution();
}
inline void PayloadResponse::_internal_set_solution(int32_t value) {
  
  _impl_.solution_ = value;
}
inline void PayloadResponse::set_solution(int32_t value) {
  _internal_set_solution(value);
  // @@protoc_insertion_point(field_set:PayloadResponse.solution)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_payload_2eproto
