name: Build

on:
  push:
    branches: "**"
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  release:
    name: zeromq-playground pipeline
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get vcpkg
        run: |
             git clone https://github.com/microsoft/vcpkg "$HOME/vcpkg"
             export VCPKG_ROOT="$HOME/vcpkg"

      - name: Configure CMake and fetch dependencies
        run: cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=$HOME/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: cmake --build build
